### SMS 발송 (성공)
POST http://localhost:8082/sms?phone=01012345678&message=테스트메시지
Authorization: Basic YXV0b2V2ZXI6NTY3OA==
Content-Type: application/x-www-form-urlencoded

### SMS 발송 (인증 실패)
POST http://localhost:8082/sms?phone=01098765432&message=실패테스트
Authorization: Basic d3Jvbmc6dXNlcjoxMjM0
Content-Type: application/x-www-form-urlencoded
